apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ui
  namespace: argocd
spec:
  rules:
    - host: argocd.telperon.com
      https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443